"""evaluacion por equipos y team_label

Revision ID: d22d7e409651
Revises: e3d7dadf4c56
Create Date: 2026-08-23 22:55:19.798062
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'd22d7e409651'
down_revision: str | None = 'e3d7dadf4c56'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessments', sa.Column('team_mode', sa.Boolean(), nullable=False))
    op.add_column('attempts', sa.Column('team_label', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attempts', 'team_label')
    op.drop_column('assessments', 'team_mode')
    # ### end Alembic commands ###
